// ─────────────────────────────────────────────────────────────────────────────
// Forge AI Provider — Type Definitions
// ─────────────────────────────────────────────────────────────────────────────

/** AI analysis result */
export interface AIResult {
  content: string;
  model: string;
  tokens_used: { input: number; output: number; total: number };
  duration_ms: number;
}

/** Structured security finding from AI analysis */
export interface AISecurityFinding {
  title: string;
  description: string;
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
  attack_vector: string;
  attack_category: string;
  cwe_id?: string;
  cve_id?: string;
  cvss_score?: number;
  exploitable: boolean;
  exploitation_proof?: string;
  exploitation_steps?: string[];
  remediation: string;
  remediation_effort: 'quick_fix' | 'moderate' | 'significant' | 'architectural';
  mitre_tactic?: string;
  mitre_technique?: string;
  nist_controls?: string[];
  evidence?: {
    request?: string;
    response?: string;
    details?: string;
  };
}

/** Exploit plan generated by AI for a target */
export interface ExploitPlan {
  target: string;
  tests: Array<{
    id: string;
    name: string;
    description: string;
    category: string;
    risk_level: 'none' | 'low' | 'medium' | 'high';
    steps: string[];
  }>;
  estimated_duration_seconds: number;
}

/** Risk assessment for a vulnerability or finding */
export interface RiskAssessment {
  overall_risk: 'critical' | 'high' | 'medium' | 'low' | 'info';
  exploitability: number; // 0-10
  impact: number;         // 0-10
  confidence: number;     // 0-100
  reasoning: string;
  recommendations: string[];
}

/** Configuration for the AI provider */
export interface AIProviderConfig {
  api_key: string;
  model?: string;
  max_tokens?: number;
  temperature?: number;
  token_budget?: number; // Max tokens per session/campaign
}

/** Token usage tracking */
export interface TokenBudget {
  limit: number;
  used: number;
  remaining: number;
}

/** Core AI provider interface — all implementations must satisfy this */
export interface ForgeAIProvider {
  /** Analyze content with a prompt and return raw AI response */
  analyze(prompt: string, context?: Record<string, unknown>): Promise<AIResult>;

  /** Generate a structured exploit test plan for a target */
  generateTestPlan(
    agentType: string,
    target: string,
    context: Record<string, unknown>
  ): Promise<ExploitPlan>;

  /** Analyze HTTP response data for security findings */
  analyzeResponse(
    agentType: string,
    testName: string,
    requestData: string,
    responseData: string,
    context: Record<string, unknown>
  ): Promise<AISecurityFinding[]>;

  /** Assess risk of a vulnerability */
  assessRisk(
    finding: Record<string, unknown>,
    assetContext: Record<string, unknown>
  ): Promise<RiskAssessment>;

  /** Get current token usage */
  getTokenUsage(): TokenBudget;
}
