#Requires -RunAsAdministrator
<#
.SYNOPSIS
    ForgeScan Internal Scanner — Windows Service Installer

.DESCRIPTION
    Downloads and installs the ForgeScan scanner as a Windows Service
    for internal network scanning on Windows Server or Windows 10/11.

.PARAMETER ApiKey
    Scanner API key (from ForgeScan dashboard registration)

.PARAMETER ScannerId
    Scanner ID (from ForgeScan dashboard registration)

.PARAMETER PlatformUrl
    ForgeScan API endpoint URL

.PARAMETER Version
    Version tag to download (default: latest)

.EXAMPLE
    .\install-windows.ps1 -ApiKey "sk_scanner_xxx" -ScannerId "scan_xxx"

.EXAMPLE
    .\install-windows.ps1 -ApiKey "sk_scanner_xxx" -ScannerId "scan_xxx" -PlatformUrl "https://api.example.com"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$ApiKey,

    [Parameter(Mandatory = $true)]
    [string]$ScannerId,

    [string]$PlatformUrl = "https://forgescan-api.stanley-riley.workers.dev",

    [string]$Version = "latest",

    [string]$LogLevel = "info",

    [switch]$UseSealedTunnel,

    [string]$StLinkConfigPath = ""
)

$ErrorActionPreference = "Stop"

# ── Configuration ─────────────────────────────────────────────
$GitHubRepo = "Bjay0727-jay/Forge-Scan"
$ServiceName = "ForgeScanScanner"
$DisplayName = "ForgeScan Internal Scanner"
$InstallDir = "C:\Program Files\ForgeScan"
$DataDir = "C:\ProgramData\ForgeScan"
$BinaryName = "forgescan-scanner.exe"

# ── SealedTunnel mode: override platform URL ──────────────────
if ($UseSealedTunnel) {
    $PlatformUrl = "http://127.0.0.5:443"
    Write-Host "[ForgeScan] SealedTunnel mode ENABLED - platform URL overridden to loopback" -ForegroundColor Yellow
    if ($StLinkConfigPath -and (Test-Path $StLinkConfigPath)) {
        Write-Host "[ForgeScan] STLink config: $StLinkConfigPath" -ForegroundColor Green
    } else {
        Write-Host "[ForgeScan] WARNING: Install Xiid STLink manually - see deploy/xiid/README.md" -ForegroundColor Yellow
    }
}

# ── Banner ────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ======================================================" -ForegroundColor Cyan
Write-Host "    ForgeScan — Internal Scanner Installer" -ForegroundColor Cyan
Write-Host "    Windows Edition" -ForegroundColor Cyan
Write-Host "  ======================================================" -ForegroundColor Cyan
Write-Host ""

# ── Resolve version ───────────────────────────────────────────
if ($Version -eq "latest") {
    Write-Host "[ForgeScan] Fetching latest release version..." -ForegroundColor Green
    $release = Invoke-RestMethod -Uri "https://api.github.com/repos/$GitHubRepo/releases/latest"
    $Version = $release.tag_name
    if (-not $Version) {
        Write-Error "Could not determine latest version. Specify -Version explicitly."
        exit 1
    }
}
Write-Host "[ForgeScan] Installing version: $Version" -ForegroundColor Green

# ── Download binary ───────────────────────────────────────────
$AssetName = "forgescan-scanner-windows-amd64"
$DownloadUrl = "https://github.com/$GitHubRepo/releases/download/$Version/$AssetName.zip"
$TempDir = Join-Path $env:TEMP "forgescan-install"

if (Test-Path $TempDir) { Remove-Item -Recurse -Force $TempDir }
New-Item -ItemType Directory -Path $TempDir -Force | Out-Null

Write-Host "[ForgeScan] Downloading from: $DownloadUrl" -ForegroundColor Green
$ZipPath = Join-Path $TempDir "$AssetName.zip"
Invoke-WebRequest -Uri $DownloadUrl -OutFile $ZipPath -UseBasicParsing

Write-Host "[ForgeScan] Extracting..." -ForegroundColor Green
Expand-Archive -Path $ZipPath -DestinationPath $TempDir -Force

# ── Stop existing service if running ──────────────────────────
$existingService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existingService) {
    Write-Host "[ForgeScan] Stopping existing service..." -ForegroundColor Yellow
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2

    # Remove old service
    sc.exe delete $ServiceName | Out-Null
    Start-Sleep -Seconds 1
}

# ── Install binary ────────────────────────────────────────────
if (-not (Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
}
if (-not (Test-Path $DataDir)) {
    New-Item -ItemType Directory -Path $DataDir -Force | Out-Null
}

Copy-Item -Path (Join-Path $TempDir $BinaryName) -Destination (Join-Path $InstallDir $BinaryName) -Force
Write-Host "[ForgeScan] Binary installed to $InstallDir\$BinaryName" -ForegroundColor Green

# Verify
& "$InstallDir\$BinaryName" --version

# ── Write config file ─────────────────────────────────────────
$ConfigContent = @"
# ForgeScan Scanner Configuration
# Generated by install-windows.ps1 on $(Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")

[platform]
url = "$PlatformUrl"
scanner_id = "$ScannerId"

[scanner]
log_level = "$LogLevel"
data_dir = "$DataDir"
max_concurrent_tasks = 4
heartbeat_interval_secs = 30

[network]
scan_timeout_secs = 5
banner_grab = true
max_port_concurrency = 500
"@

$ConfigPath = Join-Path $DataDir "scanner.toml"
Set-Content -Path $ConfigPath -Value $ConfigContent
Write-Host "[ForgeScan] Config written to $ConfigPath" -ForegroundColor Green

# ── Store API key securely ────────────────────────────────────
# Environment variable for the service (set at machine level)
[System.Environment]::SetEnvironmentVariable("FORGESCAN_SCANNER_API_KEY", $ApiKey, "Machine")
Write-Host "[ForgeScan] API key stored as machine environment variable" -ForegroundColor Green

# ── Create Windows Service ────────────────────────────────────
$BinaryPath = "`"$InstallDir\$BinaryName`" --config `"$ConfigPath`" --platform `"$PlatformUrl`" --log-level $LogLevel"

$ServiceDeps = @("Tcpip")
if ($UseSealedTunnel) {
    $ServiceDeps += "XiidSTLink"
}

New-Service -Name $ServiceName `
    -DisplayName $DisplayName `
    -Description "ForgeScan agentless internal network vulnerability scanner" `
    -BinaryPathName $BinaryPath `
    -StartupType Automatic `
    -DependsOn $ServiceDeps

# Configure service recovery (restart on failure)
sc.exe failure $ServiceName reset= 86400 actions= restart/10000/restart/10000/restart/30000 | Out-Null

Write-Host "[ForgeScan] Windows Service created: $ServiceName" -ForegroundColor Green

# ── Start service ─────────────────────────────────────────────
Start-Service -Name $ServiceName
Write-Host "[ForgeScan] Service started!" -ForegroundColor Green

# ── Cleanup ───────────────────────────────────────────────────
Remove-Item -Recurse -Force $TempDir -ErrorAction SilentlyContinue

# ── Summary ───────────────────────────────────────────────────
Write-Host ""
Write-Host "[ForgeScan] Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "  Check status:  Get-Service $ServiceName" -ForegroundColor Cyan
Write-Host "  View logs:     Get-WinEvent -LogName Application -FilterXPath `"*[System[Provider[@Name='$ServiceName']]]`" | Select -First 20" -ForegroundColor Cyan
Write-Host "  Stop:          Stop-Service $ServiceName" -ForegroundColor Cyan
Write-Host "  Start:         Start-Service $ServiceName" -ForegroundColor Cyan
Write-Host "  Config:        $ConfigPath" -ForegroundColor Cyan
Write-Host "  Data dir:      $DataDir" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Scanner should appear in the ForgeScan dashboard within 30 seconds." -ForegroundColor Green
Write-Host ""
