#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────
# ForgeScan Scanner — STLink Client Installation
#
# Installs and configures the Xiid STLink client on a scanner
# host (Hetzner or On-Prem). STLink creates a loopback binding
# that the scanner connects to instead of the public API URL.
#
# Prerequisites:
#   - Xiid STLink installer (provided by Xiid)
#   - STLink activation code (generated by Xiid Commander)
#   - Root or sudo access
#
# Usage:
#   ./install-stlink-scanner.sh \
#     --stlink-installer /path/to/stlink-installer \
#     --activation-code <CODE_FROM_COMMANDER> \
#     --loopback-ip 127.0.0.5 \
#     --loopback-port 443
# ──────────────────────────────────────────────────────────────

set -euo pipefail

# ── Defaults ──────────────────────────────────────────────────
STLINK_INSTALLER=""
ACTIVATION_CODE=""
LOOPBACK_IP="127.0.0.5"
LOOPBACK_PORT="443"
STLINK_CONFIG=""
CONFIG_DIR="/etc/xiid"

# ── Colors ────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${GREEN}[ForgeScan/STLink]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARNING]${NC} $*"; }
err()  { echo -e "${RED}[ERROR]${NC} $*" >&2; }
banner() {
    echo -e "${CYAN}"
    echo "  ╔═══════════════════════════════════════════════════╗"
    echo "  ║  ForgeScan — STLink Client Setup                   ║"
    echo "  ║  Xiid SealedTunnel Scanner Endpoint               ║"
    echo "  ╚═══════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

# ── Parse arguments ───────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --stlink-installer)  STLINK_INSTALLER="$2"; shift 2 ;;
        --activation-code)   ACTIVATION_CODE="$2"; shift 2 ;;
        --stlink-config)     STLINK_CONFIG="$2"; shift 2 ;;
        --loopback-ip)       LOOPBACK_IP="$2"; shift 2 ;;
        --loopback-port)     LOOPBACK_PORT="$2"; shift 2 ;;
        -h|--help)
            echo "Usage: $0 --activation-code <CODE> [--stlink-installer <PATH>] [--loopback-ip <IP>] [--loopback-port <PORT>]"
            exit 0
            ;;
        *) err "Unknown argument: $1"; exit 1 ;;
    esac
done

banner

# ── Validate ──────────────────────────────────────────────────
if [[ -z "$ACTIVATION_CODE" && -z "$STLINK_CONFIG" ]]; then
    err "Provide either --activation-code or --stlink-config"
    exit 1
fi
if [[ $EUID -ne 0 ]]; then
    err "This script must be run as root (or with sudo)"
    exit 1
fi

log "Loopback binding: ${LOOPBACK_IP}:${LOOPBACK_PORT}"

# ── Create directories ────────────────────────────────────────
mkdir -p "$CONFIG_DIR"

# ── Install STLink ────────────────────────────────────────────
log ""
log "═══════════════════════════════════════════════════════"
log "  XIID STLINK CLIENT INSTALLATION"
log "═══════════════════════════════════════════════════════"
log ""

if [[ -n "$STLINK_INSTALLER" && -f "$STLINK_INSTALLER" ]]; then
    log "Running STLink installer: $STLINK_INSTALLER"
    chmod +x "$STLINK_INSTALLER"
    "$STLINK_INSTALLER" --activation "$ACTIVATION_CODE"
else
    log "STLink must be installed manually:"
    log ""
    log "  1. Upload the Xiid STLink installer to this machine"
    log "  2. Run: ./stlink-install --activation $ACTIVATION_CODE"
    log ""
    log "  Alternatively, if you have a config file from Commander:"
    if [[ -n "$STLINK_CONFIG" ]]; then
        log "  Config file: $STLINK_CONFIG"
        cp "$STLINK_CONFIG" "${CONFIG_DIR}/stlink.json"
        chmod 600 "${CONFIG_DIR}/stlink.json"
        log "  Config copied to ${CONFIG_DIR}/stlink.json"
    fi
fi

# ── Save tunnel configuration ─────────────────────────────────
cat > "${CONFIG_DIR}/tunnel.env" <<EOF
# ForgeScan SealedTunnel — Scanner Client Configuration
# Generated by install-stlink-scanner.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

STLINK_LOOPBACK_IP=${LOOPBACK_IP}
STLINK_LOOPBACK_PORT=${LOOPBACK_PORT}
STLINK_ACTIVATION_CODE=${ACTIVATION_CODE}

# The scanner should connect to:
# --platform http://${LOOPBACK_IP}:${LOOPBACK_PORT}
EOF
chmod 600 "${CONFIG_DIR}/tunnel.env"

# ── Create systemd service for STLink ─────────────────────────
# Note: The actual ExecStart path depends on where Xiid installs STLink.
# Common locations: /usr/local/bin/stlink, /opt/xiid/stlink
cat > /etc/systemd/system/stlink.service <<EOF
[Unit]
Description=Xiid SealedTunnel STLink Agent
Documentation=https://xiid.com/docs
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
# Update ExecStart path to match your STLink installation
ExecStart=/usr/local/bin/stlink
Restart=always
RestartSec=5
TimeoutStopSec=30

# Security hardening
ProtectSystem=strict
ProtectHome=true
PrivateTmp=true
ReadWritePaths=/etc/xiid /var/lib/xiid

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
log "STLink systemd service created"

# ── Verify loopback binding ───────────────────────────────────
log ""
log "After STLink is installed and started, verify the tunnel:"
log ""
log "  # Start STLink"
log "  systemctl enable stlink && systemctl start stlink"
log ""
log "  # Verify loopback binding"
log "  ss -tlnp | grep ${LOOPBACK_IP}:${LOOPBACK_PORT}"
log ""
log "  # Test connectivity through tunnel"
log "  curl -v http://${LOOPBACK_IP}:${LOOPBACK_PORT}/api/v1/scanner/heartbeat \\"
log "    -H 'X-Scanner-Key: <YOUR_API_KEY>' \\"
log "    -H 'Content-Type: application/json' \\"
log "    -d '{\"scanner_id\":\"test\"}'"
log ""
log "  # Expected: HTTP 200 from Cloudflare Workers API"
log ""

log "STLink scanner setup complete!"
log ""
log "The ForgeScan scanner should use:"
log "  --platform http://${LOOPBACK_IP}:${LOOPBACK_PORT}"
